import { Canvas } from '@react-three/fiber'
import Head from 'next/head'
import { Suspense } from 'react'
import Earth from '../components/Earth'
import Text from '../components/Text'

export default function Home() {

  return (
    <div className="relative h-screen w-[100%] bg-black z-0">
      <Head>
        <title>La Planète Terre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Text />
      <Canvas>
        <Suspense fallback={null}>
          <Earth />
        </Suspense>
      </Canvas>
    </div>
  )
}
